name: mo_cbo
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.3.3
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2024.9.24
  - certifi=2022.12.7
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.2
  - intel-openmp=2020.0
  - isort=4.3.21
  - jpeg=9e
  - lazy-object-proxy=1.4.3
  - lcms2=2.12
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libtiff=4.1.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - matplotlib-base=3.5.2
  - mccabe=0.6.1
  - munkres=1.1.4
  - ncurses=6.2
  - numexpr=2.8.4
  - numpy-base=1.21.5
  - openssl=1.1.1w
  - pillow=9.0.1
  - pip=20.0.2
  - pylint=2.4.4
  - python=3.7.7
  - readline=8.0
  - seaborn=0.12.2
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - typing_extensions=4.4.0
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - alabaster==0.7.12
      - argparse==1.4.0
      - autograd==1.3
      - babel==2.14.0
      - chardet==3.0.4
      - charset-normalizer==3.4.0
      - cma==2.7.0
      - cycler==0.10.0
      - cython==0.29.16
      - decorator==5.1.1
      - docutils==0.16
      - emcee==3.1.6
      - emukit==0.4.10
      - future==0.18.2
      - gpy==1.10.0
      - idna==2.9
      - imagesize==1.4.1
      - importlib-metadata==6.7.0
      - jinja2==2.11.1
      - joblib==0.14.1
      - kiwisolver==1.2.0
      - markupsafe==1.1.1
      - matplotlib==3.2.1
      - numpy==1.18.0
      - numpydoc==0.9.2
      - packaging==20.3
      - pandas==1.0.3
      - paramz==0.9.6
      - plotly==4.7.1
      - pydoe2==1.3.0
      - pygco==0.0.16
      - pygments==2.6.1
      - pymoo==0.4.0
      - pymop==0.2.4
      - pyparsing==2.4.6
      - python-dateutil==2.8.1
      - pytz==2019.3
      - pyyaml==5.3.1
      - requests==2.23.0
      - retrying==1.3.3
      - scikit-learn==0.22.2.post1
      - scipy==1.4.1
      - smt==0.4.3
      - snowballstemmer==2.0.0
      - sphinx==2.4.4
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==1.0.3
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.4
      - typing-extensions==4.7.1
      - urllib3==1.25.8
      - zipp==3.15.0